# Generated by Django 4.2.6 on 2023-11-21 16:20

from django.db import migrations, models
import django.db.models.deletion
import docs_metadata.models
import enumchoicefield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.CreateModel(name='Command',
        fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), (
        'action', enumchoicefield.fields.EnumChoiceField(default=docs_metadata.models.Action(2),
                                                         enum_class=docs_metadata.models.Action, max_length=8)),
            ('name', models.CharField(max_length=256, unique=True)),
            ('title', models.CharField(max_length=256, unique=True)),
            ('prefix', models.CharField(blank=True, max_length=256, null=True, unique=True)), ], ),
        migrations.CreateModel(name='Document', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('order_index', models.IntegerField()), ('file_prefix', models.CharField(max_length=256)),
            ('index_text', models.CharField(max_length=5, null=True)),
            ('text', models.TextField(max_length=512, null=True)), ('parse_mode',
                                                                    enumchoicefield.fields.EnumChoiceField(
                                                                        default=docs_metadata.models.ParseMode(1),
                                                                        enum_class=docs_metadata.models.ParseMode,
                                                                        max_length=11)),
            ('remove_buttons_before_message', models.BooleanField(default=False)),
            ('buttons', models.ManyToManyField(related_name='document_command', to='docs_metadata.command')), ],
            options={'ordering': ['order_index'], }, ), migrations.CreateModel(name='CompanyWelcome', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('readd_document_text', models.CharField(max_length=256)), ('help_text', models.TextField(max_length=2048)),
            ('start_text', models.TextField(max_length=512)), ('add_document_command', models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='add_document_command',
                to='docs_metadata.command')), ('add_next_document_command',
                                               models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                                 related_name='add_next_document_command',
                                                                 to='docs_metadata.command')), ('cancel_command',
                                                                                                models.ForeignKey(
                                                                                                    on_delete=django.db.models.deletion.PROTECT,
                                                                                                    related_name='cancel_command',
                                                                                                    to='docs_metadata.command')),
            ('end_document_command',
             models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_document_command',
                               to='docs_metadata.command')), ('help_command', models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='help_command',
                to='docs_metadata.command')), ], ), ]
