"""
Django settings for submit_job_docs project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

ENV_FILENAME = str(os.getenv('ENV_FILENAME'))
if os.path.exists(ENV_FILENAME):
    load_dotenv(ENV_FILENAME)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if str(os.getenv('DEBUG')).lower() in ('yes', 'true', 't', '1') else False
TEMPLATE_DEBUG = DEBUG
DEBUG_PROPAGATE_EXCEPTIONS = DEBUG

ALLOWED_HOSTS = str(os.getenv('ALLOWED_HOSTS')).split(',')

SITE_ID = 1

if DEBUG:
    INTERNAL_IPS = [
        '0.0.0.0',
        '127.0.0.1',
        'localhost',
    ]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_rest_passwordreset',
]
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

# application include in submit_job_docs
INCLUDE_INSTALLED_APPS = [
    'docs_metadata',
    'docs_api',
    'docs_site',
]
INSTALLED_APPS += INCLUDE_INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE

ROOT_URLCONF = 'submit_job_docs.urls'

TEMPLATE_DIR = 'templates'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, TEMPLATE_DIR)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'submit_job_docs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# noinspection PyPackageRequirements
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'TEST': {
            'NAME': os.getenv('TEST_DB_NAME', default='submit_job_docs_test'),
        },
    }
}

# redis for cache
REDIS_CACHE_HOST = os.getenv('REDIS_CACHE_HOST')
REDIS_CACHE_PORT = os.getenv('REDIS_CACHE_PORT', default='6379')
REDIS_CACHE_USER = os.getenv('REDIS_CACHE_USER')
REDIS_CACHE_PASSWORD = os.getenv('REDIS_CACHE_PASSWORD')

REDIS_CACHE_AUTH = ''.join([REDIS_CACHE_USER, ':', REDIS_CACHE_PASSWORD, '@']) if REDIS_CACHE_USER else ''

REDIS_CACHE = {
    'BACKEND': 'django.core.cache.backends.redis.RedisCache',
    'LOCATION': f'redis://{REDIS_CACHE_AUTH}{REDIS_CACHE_HOST}:{REDIS_CACHE_PORT}',
}

LOC_MEM_CACHE = {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
}

USE_CACHE = LOC_MEM_CACHE
if not DEBUG and REDIS_CACHE_HOST:
    USE_CACHE = REDIS_CACHE

CACHES = {
    'default': USE_CACHE
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = os.getenv('TIME_ZONE', default='Europe/Moscow')

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_PATH = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, STATIC_PATH)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '_'.join([TEMPLATE_DIR, STATIC_PATH])),
)

MEDIA_URL = '/files/'
MEDIA_PATH = 'upload_files/'
MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_PATH)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': f'{os.getenv("THROTTLE_RATE_USER_PERMINUTE", default="20")}/minute',
        'anon': f'{os.getenv("THROTTLE_RATE_ANON_PERMINUTE", default="10")}/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': os.getenv('PAGINATION_PAGE_SIZE', default=100),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
)

AUTH_USER_MODEL = 'auth.User'

LOGIN_URL = '/metadata/login/'

API_URL = 'api/'
DEFAULT_API_VERSION = os.getenv('DEFAULT_API_VERSION', default=1)

LOGIN_REDIRECT_URL = '/metadata/'  # '/metadata/profile/'

LOGOUT_REDIRECT_URL = LOGIN_URL
