name: Test project on push

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8(bugbear) Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          flake8-version: "7.1.2"
          exclude: ".env,.run,migrations"
          max-line-length: "120"
          path: "."
          plugins: "flake8-bugbear==24.12.12"
